# GitHub Action para gerar a "Snake" com cores personalizadas
name: Generate Snake

on:
  # Executa a cada 24 horas (ajuste conforme desejar)
  schedule:
    - cron: "17 7 * * *"
    
  # Permite rodar manualmente (Actions > "Run workflow")
  workflow_dispatch:

  # Executa quando há push na branch main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
      # 1. Faz checkout do seu repositório
      - uses: actions/checkout@v2

      # 2. Gera os arquivos SVG da cobra usando o Platane/snk
      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # Mudei pra azul os commits e cinza a cobra
            dist/github-contribution-grid-snake.svg?color_snake=%23202020,%23333333,%23666666,%23888888,%23aaaaaa&color_dots=%23008e9e,%235cdcf4
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23202020,%23333333,%23666666,%23888888,%23aaaaaa&color_dots=%23008e9e,%235cdcf4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. (Opcional) Exibe o status do repositório para debug
      - run: git status

      # 4. Publica os arquivos gerados na branch "output"
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
